config/routes.rb
Life2nite::Application.routes.draw do
  
  resources :events

  devise_for :promotors

  devise_for :users

  root :to => 'pages#home'
  
  get 'about' => 'pages#about'
  get 'blog' => 'pages#blog'
  get 'home' => 'pages#home'

  

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :address, :city, :celebappearance, :cost1, :cost2, :description, :drinkspecials, :drinkspecialsuntil, :everybodyinfree, :everyfreeuntil, :guestlist, :guestlistcutofftime, :industryevent, :ladiesinfree, :partyendtime, :partystarttime, :pname, :state, :zipcode
end

app/models/promotor.rb
class Promotor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def blog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :pname %><br />
    <%= f.text_field :pname %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :partystarttime %><br />
    <%= f.datetime_select :partystarttime %>
  </div>
  <div class="field">
    <%= f.label :partyendtime %><br />
    <%= f.datetime_select :partyendtime %>
  </div>
  <div class="field">
    <%= f.label :ladiesinfree %><br />
    <%= f.check_box :ladiesinfree %>
  </div>
  <div class="field">
    <%= f.label :guestlistcutofftime %><br />
    <%= f.datetime_select :guestlistcutofftime %>
  </div>
  <div class="field">
    <%= f.label :everybodyinfree %><br />
    <%= f.check_box :everybodyinfree %>
  </div>
  <div class="field">
    <%= f.label :everyfreeuntil %><br />
    <%= f.datetime_select :everyfreeuntil %>
  </div>
  <div class="field">
    <%= f.label :industryevent %><br />
    <%= f.check_box :industryevent %>
  </div>
  <div class="field">
    <%= f.label :celebappearance %><br />
    <%= f.check_box :celebappearance %>
  </div>
  <div class="field">
    <%= f.label :drinkspecials %><br />
    <%= f.text_field :drinkspecials %>
  </div>
  <div class="field">
    <%= f.label :drinkspecialsuntil %><br />
    <%= f.datetime_select :drinkspecialsuntil %>
  </div>
  <div class="field">
    <%= f.label :guestlist %><br />
    <%= f.check_box :guestlist %>
  </div>
  <div class="field">
    <%= f.label :cost1 %><br />
    <%= f.text_field :cost1 %>
  </div>
  <div class="field">
    <%= f.label :cost2 %><br />
    <%= f.text_field :cost2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<HEAD>
  <script type="text/javascript" src="assets/twitterbootstrap/js/bootstrap-tab.js"></script>
</HEAD>
<div class="hero-unit">
<h2>Listing events</h2>

<% @events.each do |event| %>
  <div class="media">
    <a class="pull-left" href="#">
        <img class="media-object" src="/assets/27.jpg">
    </a>
    <div class="media-body">
    <h4 class="media-heading">Media heading</h4>
    

  <ul class="nav nav-tabs" id="myTab">
    <li class="active"><a href="#page1">Page 1</a></li>
    <li><a href="#page2">Page 2</a></li>
    <li><a href="#page3">Page 3</a></li>
  </ul>
 
  <div class="tab-content">
    <div class="tab-pane active" id="page1">
      <table class="table-tablestriped">
        <tr>
          <th>Description</th>
          <th>Pname</th>
          <th>Address</th>
          <th>City</th>
          <th>State</th>
          <th>Zipcode</th>
          <th>Partystarttime</th>
          <th>Partyendtime</th>
        </tr>
        <tr>
          <td><%= event.description %></td>
          <td><%= event.pname %></td>
          <td><%= event.address %></td>
          <td><%= event.state %></td>
          <td><%= event.city %></td>
          <td><%= event.zipcode %></td>
          <td><%= event.partystarttime %></td>
          <td><%= event.partyendtime %></td>
        </tr>
      </table>
    </div>
    <div class="tab-pane" id="page2">
      <table class="table-tablestriped">
        <tr>
          <th>Ladiesinfree</th>
          <th>Guestlistcutofftime</th>
          <th>Everybodyinfree</th>
          <th>Everyfreeuntil</th>
          <th>Industryevent</th>
          <th>Celebappearance</th>
          <th>Drinkspecials</th>
          <th>Drinkspecialsuntil</th>
        </tr>
        <tr>
          <td><%= event.ladiesinfree %></td>
          <td><%= event.guestlistcutofftime %></td>
          <td><%= event.everybodyinfree %></td>
          <td><%= event.everyfreeuntil %></td>
          <td><%= event.industryevent %></td>
          <td><%= event.celebappearance %></td>
          <td><%= event.drinkspecials %></td>
          <td><%= event.drinkspecialsuntil %></td>
        </tr>
      </table>        
    </div>
    <div class="tab-pane" id="page3">
      <table class="table-tablestriped">
        <tr>
          <th>Guestlist</th>
          <th>Cost1</th>
          <th>Cost2</th>
        </tr>
        <tr>
          <td><%= event.guestlist %></td>
          <td><%= event.cost1 %></td>
          <td><%= event.cost2 %></td>
        </tr>    
    </div>
  </div>
  <table> 
    <tr>
      <td><%= link_to 'Show', event %></td>
      <td><%= link_to 'Edit', edit_event_path(event) %></td>
      <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  </table>


</div>     
</div>
</div>

<% end %>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

<p>
  <b>Pname:</b>
  <%= @event.pname %>
</p>

<p>
  <b>Address:</b>
  <%= @event.address %>
</p>

<p>
  <b>City:</b>
  <%= @event.city %>
</p>

<p>
  <b>State:</b>
  <%= @event.state %>
</p>

<p>
  <b>Zipcode:</b>
  <%= @event.zipcode %>
</p>

<p>
  <b>Partystarttime:</b>
  <%= @event.partystarttime.strftime("at %I:%M%p") %>
</p>

<p>
  <b>Partyendtime:</b>
  <%= @event.partyendtime, :format => :short %>
</p>

<p>
  <b>Ladiesinfree:</b>
  <%= @event.ladiesinfree %>
</p>

<p>
  <b>Guestlistcutofftime:</b>
  <%= @event.guestlistcutofftime, :format => :short %>
</p>

<p>
  <b>Everybodyinfree:</b>
  <%= @event.everybodyinfree %>
</p>

<p>
  <b>Everyfreeuntil:</b>
  <%= @event.everyfreeuntil, :format => :short %>
</p>

<p>
  <b>Industryevent:</b>
  <%= @event.industryevent %>
</p>

<p>
  <b>Celebappearance:</b>
  <%= @event.celebappearance %>
</p>

<p>
  <b>Drinkspecials:</b>
  <%= @event.drinkspecials %>
</p>

<p>
  <b>Drinkspecialsuntil:</b>
  <%= @event.drinkspecialsuntil, :format => :short %>
</p>

<p>
  <b>Guestlist:</b>
  <%= @event.guestlist %>
</p>

<p>
  <b>Cost1:</b>
  <%= @event.cost1 %>
</p>

<p>
  <b>Cost2:</b>
  <%= @event.cost2 %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		
		
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <%= link_to image_tag("life2nite_smallest.png"), root_path, class: "brand" %>


      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <ul class="nav">
	        <li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Blog", blog_path %></p></li>

		</ul>

		 <ul class="nav pull-right">

          <% if user_signed_in? %>
              <li><%= link_to "Edit User Profile", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% elsif promotor_signed_in? %>
             
              <li><%= link_to "Edit Promotor Profile", edit_promotor_registration_path %></li>
              <li><%= link_to "Logout", destroy_promotor_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to "Promotor Login", new_promotor_session_path %></li>
	            <li><%= link_to "User Login", new_user_session_path %></li>
			    <% end %>



		</ul>

      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Life2nite</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>

<div class="container">

	<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
	<% end %>
	
<%= yield %>

</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/blog.html.erb
<h1>Pages#blog</h1>
<p>Find me in app/views/pages/blog.html.erb</p>

app/views/pages/home.html.erb
<%= javascript_include_tag 'bootstrap-tab.js' %>
<CENTER>
    <H1> Welcome to Life2Nite</H1>
</CENTER>


<div id="myCarousel" class="carousel slide">
    
  <div class="carousel-inner">

    <div class="item active">
      <img src="/assets/carousel1.jpg" alt="">
      <div class="carousel-caption">
        <H4>Title 1</H4>
        <p>Here is the first image!</p>
      </div>
    </div>

    <div class="item">
      <img src="/assets/carousel2.jpg" alt="">
      <div class="carousel-caption">
        <H4>Title 2</H4>
        <p>Caption text here</p>
      </div>
    </div>

    <div class="item">
      <img src="/assets/carousel3.jpg" alt="">
      <div class="carousel-caption">
      <H4>Title 3</H4>
        <p>Caption text here</p>
      </div>
    </div>

  </div><!-- /.carousel-inner -->
  
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>

</div><!-- /.carousel -->

<div class="accordion" id="accordion2">
<div class="accordion-group">
<div class="accordion-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
Collapsible Group Item #1
</a>
</div>
<div id="collapseOne" class="accordion-body collapse in">
<div class="accordion-inner">
Anim pariatur cliche...
</div>
</div>
</div>
<div class="accordion-group">
<div class="accordion-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
Collapsible Group Item #2
</a>
</div>
<div id="collapseTwo" class="accordion-body collapse">
<div class="accordion-inner">
Anim pariatur cliche...
</div>
</div>
</div>
</div>


<ul class="nav nav-pills" id="myTab">
<li class="active"><a href="#home">Home</a></li>
<li><a href="#profile">Profile</a></li>
<li><a href="#messages">Messages</a></li>
<li><a href="#settings">Settings</a></li>
</ul>
 
<div class="tab-content">
<div class="tab-pane active" id="home">
<p>
  This is sample text for this tab
</p>
</div>
<div class="tab-pane" id="profile">
<p>
  This2 is sample text for this tab
</p>
</div>
<div class="tab-pane" id="messages">
  <p>
  This3 is sample text for this tab
</p>
</div>
<div class="tab-pane" id="settings">
  <p>
  This4 is sample text for this tab
</p>
</div>
</div>